nelmio_api_doc:
  documentation:
    info:
      title: 'Fruits and Vegetables'
      description: 'This is the API documentation'
      version: '1.0.0'
  areas:
    path_patterns:
      - ^/api(?!/doc$)