services:
  db:
    container_name: fruit-and-veg-db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-fruit_and_veg}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: >
        bash -c 'mysql -u"${MYSQL_USER:-user}" -p"${MYSQL_PASSWORD:-password}" -e "SHOW DATABASES;"'
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - fruit-and-veg-network
  app:
    container_name: fruit-and-veg-app
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8080}:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_ENV=${APP_ENV:-dev}
    volumes:
      - ./:/app
    entrypoint: ./docker/entrypoint.sh
    command: "php -S 0.0.0.0:8080 -t /app/public"
    networks:
      - fruit-and-veg-network
  app-test:
    container_name: fruit-and-veg-app-test
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - APP_ENV=test
    volumes:
      - ./:/app
    entrypoint: ./docker/entrypoint-test.sh
networks:
  fruit-and-veg-network:
volumes:
  db_data: